name: Deploy component

on:
  workflow_call:

jobs:
  build-docker-images:
    uses: ./.github/workflows/build-images.yaml
  
  trivy-scan:
    uses: ./.github/workflows/trivy.yaml
  
  # testing:
  #   uses: ./.github/workflows/testing.yaml
  
  deploy-to-acr:
    needs:
      - build-docker-images
      - trivy-scan
    uses: ./.github/workflows/deploy.yaml