name: Deploy component

on:
  workflow_call:

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-images.yaml
  
  trivy-scan:
    needs:
      - build-docker-image
    uses: ./.github/workflows/trivy.yaml
  
  unit-testing:
    uses: ./.github/workflows/testing.yaml
  
  deploy-to-acr:
    needs:
      - trivy-scan
      - unit-testing
    uses: ./.github/workflows/deploy.yaml