name: Deploy component to Kubernetes

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      # SETUP #
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      # HELM LOGIC #
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.12.0" # Specify the Helm version you want to use

      - name: Deploy Helm chart
        run: |
          helm upgrade --install devsu-test ./microservice-chart \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }}